### ISSUE TITLE
Updates regarding the bi-allelic mutation status of drivers

### ISSUE THREAD

**Issue by sehilyi** [sehilyi/goscan#88]
**Current**
We currently display “⊙” only when “biallelic” is “yes”, and we do not display it when the value is “no” or `undefined`.

**Changes**
We want to show “⊙” for bi-allelic ("yes", **non-case-sensitive**),
“.” for NOT bi-allelic (aka. mono-allelic) ("no", **non-case-sensitive**), and
no symbol when `undefined`

We also will need to clarify this in our documentation.

(cc @dominikglodzikhms @vstevensf)

**Comment by vstevensf** [comment]
Below (for driver NF1 in chromosome 18) are examples of the current behavior with the case sensitivity regarding the value in the biallelic column. If the "yes" is not all lowercase in the driver file (e.g. "YES", "Yes"), that inputted item will show up next to the driver name instead of the  “⊙”.

<img width="287" alt="Screen Shot 2023-03-01 at 4 27 25 PM" src="https://user-images.githubusercontent.com/43185675/222270040-495bed0d-7d69-40b7-9e31-1ebdb61fffa2.png">
<img width="435" alt="Screen Shot 2023-03-01 at 4 31 46 PM" src="https://user-images.githubusercontent.com/43185675/222270043-b73b1fe1-95c5-4a9d-9efd-918a7b1a7579.png">

**Comment by sehilyi** [comment]
> OK, so the desired behavior would be:
“⊙” for bi-allelic
“.” for NOT bi-allelic (aka. mono-allelic)
no symbol when undefined

from @dominikglodzikhms

**Comment by sehilyi** [comment]
This is now supported by the latest commit.

![Screenshot 2023-03-19 at 18 20 12](https://user-images.githubusercontent.com/9922882/226213125-21afde58-855b-4ef7-9467-4dc86c26ed7a.png)
